"""Generate scripts/create_label_form.gs from the importer's form spec.

Titles and choices come from scripts/import_form_labels.py (get_form_spec),
so the Google Form and the CSV importer cannot drift apart.

Usage:
    python scripts/build_form_script.py
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GS_PATH = ROOT / "scripts" / "create_label_form.gs"


def _load_importer():
    path = ROOT / "scripts" / "import_form_labels.py"
    spec = importlib.util.spec_from_file_location("import_form_labels", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _js_string(value: str) -> str:
    """Single-quoted JS string with escapes."""
    return json.dumps(value, ensure_ascii=False)


def _js_string_array(values: list[str]) -> str:
    inner = ", ".join(_js_string(v) for v in values)
    return f"[{inner}]"


def render_apps_script(form_spec: dict | None = None) -> str:
    """Return the full Apps Script source for createLabelForm()."""
    if form_spec is None:
        form_spec = _load_importer().get_form_spec()

    title = form_spec["title"]
    description = form_spec["description"]
    questions = form_spec["questions"]
    if len(questions) != 12:
        raise ValueError(f"expected 12 questions, got {len(questions)}")

    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Auto-generated by scripts/build_form_script.py — do not edit by hand.")
    lines.append(" * Regenerate:  python scripts/build_form_script.py")
    lines.append(" * Source of truth: scripts/import_form_labels.py (get_form_spec).")
    lines.append(" *")
    lines.append(" * How to run this (first time with Apps Script)")
    lines.append(" * ---------------------------------------------")
    lines.append(" * 1. Open https://script.google.com while signed into the Google")
    lines.append(" *    account that should own the form.")
    lines.append(" * 2. Click New project. Rename it if you like (e.g. Parks label form).")
    lines.append(" * 3. Delete any placeholder code in Code.gs.")
    lines.append(" * 4. Paste this entire file into the editor and save (Ctrl/Cmd+S).")
    lines.append(" * 5. In the toolbar function dropdown, choose createLabelForm.")
    lines.append(" * 6. Click Run. Google will ask you to authorize the script:")
    lines.append(" *    Review permissions → pick your account → Advanced →")
    lines.append(" *    Go to <project> (unsafe) → Allow.")
    lines.append(" *    (This is normal for a script you pasted yourself.)")
    lines.append(" * 7. When it finishes, open View → Logs (or Execution log).")
    lines.append(" *    Copy the three links: form edit URL, public form URL, and")
    lines.append(" *    the responses spreadsheet URL.")
    lines.append(" * 8. Share the public form URL with labelers. Export responses as")
    lines.append(" *    CSV from the sheet (File → Download → CSV) and import with")
    lines.append(" *    scripts/import_form_labels.py.")
    lines.append(" *")
    lines.append(" * Re-running createLabelForm() creates another form + sheet; it does")
    lines.append(" * not update an existing form.")
    lines.append(" */")
    lines.append("")
    lines.append("function createLabelForm() {")
    lines.append(f"  var form = FormApp.create({_js_string(title)});")
    lines.append(f"  form.setDescription({_js_string(description)});")
    lines.append("  form.setCollectEmail(false);")
    lines.append("")

    for index, q in enumerate(questions, start=1):
        var_name = f"q{index}"
        qtype = q["type"]
        qtitle = q["title"]
        required = "true" if q.get("required") else "false"
        help_text = q.get("help")
        validation = q.get("validation")
        choices = q.get("choices") or []

        lines.append(f"  // {index}. {qtitle}")
        if qtype == "checkbox":
            lines.append(f"  var {var_name} = form.addCheckboxItem();")
            lines.append(f"  {var_name}.setTitle({_js_string(qtitle)});")
            lines.append(f"  {var_name}.setChoiceValues({_js_string_array(choices)});")
            lines.append(f"  {var_name}.setRequired({required});")
            if validation == "exactly_3":
                lines.append(
                    f"  {var_name}.setValidation("
                    "FormApp.createCheckboxValidation()"
                    ".requireSelectExactly(3)"
                    '.setHelpText("Pick exactly 3 parks.")'
                    ".build());"
                )
            elif validation and validation.startswith("at_most_"):
                limit = int(validation.removeprefix("at_most_"))
                lines.append(
                    f"  {var_name}.setValidation("
                    "FormApp.createCheckboxValidation()"
                    f".requireSelectAtMost({limit})"
                    f'.setHelpText("Pick up to {limit}.")'
                    ".build());"
                )
            elif validation:
                raise ValueError(f"unknown checkbox validation: {validation!r}")
        elif qtype == "multiple_choice":
            lines.append(f"  var {var_name} = form.addMultipleChoiceItem();")
            lines.append(f"  {var_name}.setTitle({_js_string(qtitle)});")
            lines.append(f"  {var_name}.setChoiceValues({_js_string_array(choices)});")
            lines.append(f"  {var_name}.setRequired({required});")
        elif qtype == "text":
            lines.append(f"  var {var_name} = form.addTextItem();")
            lines.append(f"  {var_name}.setTitle({_js_string(qtitle)});")
            lines.append(f"  {var_name}.setRequired({required});")
            if validation == "number_gt_0":
                lines.append(
                    f"  {var_name}.setValidation("
                    "FormApp.createTextValidation()"
                    ".requireNumberGreaterThan(0)"
                    '.setHelpText("Enter a number greater than 0, or leave blank.")'
                    ".build());"
                )
        else:
            raise ValueError(f"unknown question type: {qtype!r}")

        if help_text:
            lines.append(f"  {var_name}.setHelpText({_js_string(help_text)});")
        lines.append("")

    lines.append('  var sheet = SpreadsheetApp.create(form.getTitle() + " (responses)");')
    lines.append(
        "  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());"
    )
    lines.append("")
    lines.append('  Logger.log("Form edit link: " + form.getEditUrl());')
    lines.append('  Logger.log("Form public link: " + form.getPublishedUrl());')
    lines.append('  Logger.log("Responses sheet: " + sheet.getUrl());')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_apps_script(path: Path = GS_PATH) -> Path:
    path.write_text(render_apps_script(), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if create_label_form.gs does not match a fresh render",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=GS_PATH,
        help="Output path (default: scripts/create_label_form.gs)",
    )
    args = parser.parse_args(argv)

    rendered = render_apps_script()
    if args.check:
        if not args.out.exists():
            print(f"missing {args.out}", file=sys.stderr)
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"{args.out} is out of date. Run: python scripts/build_form_script.py",
                file=sys.stderr,
            )
            return 1
        print(f"{args.out} is up to date")
        return 0

    args.out.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.out} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
