/*
 * Auto-generated by scripts/build_form_script.py — do not edit by hand.
 * Regenerate:  python scripts/build_form_script.py
 * Source of truth: scripts/import_form_labels.py (get_form_spec).
 *
 * How to run this (first time with Apps Script)
 * ---------------------------------------------
 * 1. Open https://script.google.com while signed into the Google
 *    account that should own the form.
 * 2. Click New project. Rename it if you like (e.g. Parks label form).
 * 3. Delete any placeholder code in Code.gs.
 * 4. Paste this entire file into the editor and save (Ctrl/Cmd+S).
 * 5. In the toolbar function dropdown, choose createLabelForm.
 * 6. Click Run. Google will ask you to authorize the script:
 *    Review permissions → pick your account → Advanced →
 *    Go to <project> (unsafe) → Allow.
 *    (This is normal for a script you pasted yourself.)
 * 7. When it finishes, open View → Logs (or Execution log).
 *    Copy the three links: form edit URL, public form URL, and
 *    the responses spreadsheet URL.
 * 8. Share the public form URL with labelers. Export responses as
 *    CSV from the sheet (File → Download → CSV) and import with
 *    scripts/import_form_labels.py.
 *
 * Re-running createLabelForm() creates another form + sheet; it does
 * not update an existing form.
 */

function createLabelForm() {
  var form = FormApp.create("Help me test a national park recommender");
  form.setDescription("Picture one trip you would really take. Answer for that trip, then pick the 3 parks that fit it best. You don't need to have visited them. About 3 minutes. No names or emails are collected.");
  form.setCollectEmail(false);

  // 1. Terrains you want
  var q1 = form.addCheckboxItem();
  q1.setTitle("Terrains you want");
  q1.setChoiceValues(["Mountains / alpine", "Canyon", "Cave", "Chaparral / scrub", "Coast", "Desert", "Forest", "Island", "Prairie / grassland", "Rainforest", "Tundra", "Urban", "Volcano", "Wetland"]);
  q1.setRequired(false);

  // 2. Activities you want
  var q2 = form.addCheckboxItem();
  q2.setTitle("Activities you want");
  q2.setChoiceValues(["4x4 / off-road", "Archaeology", "Backpacking", "Beach", "Bears", "Biking", "Birding", "Boardwalk", "Boat", "Camping", "Climbing", "Easy walk", "Family-friendly", "Fishing", "Geothermal", "Giant trees", "Glacier", "Hiking", "History", "Hot springs", "Kayak", "Paleontology", "Photography", "Sand dunes", "Scenic drive", "Snorkeling", "Stargazing", "Sunrise / sunset views", "Water / lakes", "Waterfalls", "Wilderness", "Wildflowers", "Wildlife", "Winter activities"]);
  q2.setRequired(false);

  // 3. Difficulty
  var q3 = form.addMultipleChoiceItem();
  q3.setTitle("Difficulty");
  q3.setChoiceValues(["Easy", "Moderate", "Challenging"]);
  q3.setRequired(true);

  // 4. Trip length
  var q4 = form.addMultipleChoiceItem();
  q4.setTitle("Trip length");
  q4.setChoiceValues(["Day trip", "Weekend (2–3 days)", "About a week (4–7 days)", "Longer than a week"]);
  q4.setRequired(true);

  // 5. Crowd preference
  var q5 = form.addMultipleChoiceItem();
  q5.setTitle("Crowd preference");
  q5.setChoiceValues(["Prefer quiet / low crowds", "Medium is fine", "Busy / popular is fine"]);
  q5.setRequired(true);

  // 6. Budget
  var q6 = form.addMultipleChoiceItem();
  q6.setTitle("Budget");
  q6.setChoiceValues(["Low", "Mid", "High"]);
  q6.setRequired(true);
  q6.setHelpText("Your total travel cost: gas or flights, lodging and food. Not the entrance fee.");

  // 7. Month you want to go
  var q7 = form.addMultipleChoiceItem();
  q7.setTitle("Month you want to go");
  q7.setChoiceValues(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", "No preference / not sure"]);
  q7.setRequired(true);

  // 8. Starting city
  var q8 = form.addMultipleChoiceItem();
  q8.setTitle("Starting city");
  q8.setChoiceValues(["San Diego", "Los Angeles", "Phoenix", "Denver", "Seattle", "Salt Lake City", "New York City", "Anywhere"]);
  q8.setRequired(true);

  // 9. Max drive hours
  var q9 = form.addTextItem();
  q9.setTitle("Max drive hours");
  q9.setRequired(false);
  q9.setValidation(FormApp.createTextValidation().requireNumberGreaterThan(0).setHelpText("Enter a number greater than 0, or leave blank.").build());
  q9.setHelpText("Positive number of hours (e.g. 8). Leave blank when Starting city is Anywhere.");

  // 10. Allow remote parks
  var q10 = form.addMultipleChoiceItem();
  q10.setTitle("Allow remote parks");
  q10.setChoiceValues(["Yes", "No"]);
  q10.setRequired(true);

  // 11. Allow parks that need permits
  var q11 = form.addMultipleChoiceItem();
  q11.setTitle("Allow parks that need permits");
  q11.setChoiceValues(["Yes", "No"]);
  q11.setRequired(true);

  // 12. Top 3 parks
  var q12 = form.addCheckboxItem();
  q12.setTitle("Top 3 parks");
  q12.setChoiceValues(["Acadia National Park", "National Park of American Samoa", "Arches National Park", "Badlands National Park", "Big Bend National Park", "Biscayne National Park", "Black Canyon of the Gunnison National Park", "Bryce Canyon National Park", "Canyonlands National Park", "Capitol Reef National Park", "Carlsbad Caverns National Park", "Channel Islands National Park", "Congaree National Park", "Crater Lake National Park", "Cuyahoga Valley National Park", "Death Valley National Park", "Denali National Park", "Dry Tortugas National Park", "Everglades National Park", "Gates of the Arctic National Park", "Gateway Arch National Park", "Glacier National Park", "Glacier Bay National Park", "Grand Canyon National Park", "Grand Teton National Park", "Great Basin National Park", "Great Sand Dunes National Park", "Great Smoky Mountains National Park", "Guadalupe Mountains National Park", "Haleakala National Park", "Hawaii Volcanoes National Park", "Hot Springs National Park", "Indiana Dunes National Park", "Isle Royale National Park", "Joshua Tree National Park", "Katmai National Park", "Kenai Fjords National Park", "Kings Canyon National Park", "Kobuk Valley National Park", "Lake Clark National Park", "Lassen Volcanic National Park", "Mammoth Cave National Park", "Mesa Verde National Park", "Mount Rainier National Park", "New River Gorge National Park", "North Cascades National Park", "Olympic National Park", "Petrified Forest National Park", "Pinnacles National Park", "Redwood National Park", "Rocky Mountain National Park", "Saguaro National Park", "Sequoia National Park", "Shenandoah National Park", "Theodore Roosevelt National Park", "Virgin Islands National Park", "Voyageurs National Park", "White Sands National Park", "Wind Cave National Park", "Wrangell-St. Elias National Park", "Yellowstone National Park", "Yosemite National Park", "Zion National Park"]);
  q12.setRequired(true);
  q12.setValidation(FormApp.createCheckboxValidation().requireSelectExactly(3).setHelpText("Pick exactly 3 parks.").build());

  var sheet = SpreadsheetApp.create(form.getTitle() + " (responses)");
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());

  Logger.log("Form edit link: " + form.getEditUrl());
  Logger.log("Form public link: " + form.getPublishedUrl());
  Logger.log("Responses sheet: " + sheet.getUrl());
}
